#!/bin/sh

set -x
set -e

CUSTOM_DIR=/opt/echelon/usr

CUSTOM_ARGS=
CUSTOM_ARGS="$CUSTOM_ARGS -DHIREDIS_ROOT_DIR=$CUSTOM_DIR"
CUSTOM_ARGS="$CUSTOM_ARGS -DHIREDIS_SSL_ROOT_DIR=$CUSTOM_DIR"
CUSTOM_ARGS="$CUSTOM_ARGS -DLIBUV_DIR=$CUSTOM_DIR"
CUSTOM_ARGS="$CUSTOM_ARGS -DRABBITMQ_DIR=$CUSTOM_DIR"

cmake $CUSTOM_ARGS ../code

exit 0
